### PR TITLE
SkyColor plugin

### PR DESCRIPTION
**Pull request by xyzbtw**
SkyColor plugin to change the sky

### CODE REVIEW

**Comment by mdo992** [comment]
u probably should
- not rely on forge api, earthhack has its own event bus I think
- change archivesBaseName to lower case
- beautify code
- maybe remove the fernflower watermark

**Comment by xyzbtw** [comment]
Thanks! Ill try doing that right now

**Comment by mdo992** [comment]
do you just want me to make a pr fixing all of this later

**Comment by xyzbtw** [comment]
it would be nice, but I don't know how to code and it's nice for me to learn this!

**Pull request closed without merging**
