### PR TITLE
[1.8.0] Make a PingBypass password mandatory, fixes #136

### LINKED ISSUE #136: [BUG] PingBypass account vulnerability
### FIX ASAP BECAUSE AN IP LEAK COULD GET TO COORDS LEAK AND ... ?? 

**Describe the bug**  
If you try to connect to a pingbypass server (account1) and you have an other account on the client (account2) you will be able to use the server account

**To Reproduce**  
1. Login with an account on the pingbypass server and launch the server
2. Login with an other account on the minecraft client
3. Connect to the pingbypass
4. You end up using the account on the server

**Expected behavior**  
You can't connect to the pingbypass or at least to MC servers

**Describe the solution you'd like**
-Maybe a password? (I think it would not be a so good fix)
-Unable to connect to the pingbypass server (This would not be good because people can use this pingbypass bug to quickly use alts)
-Add the option to use this but the setting is disabled by default (good solution, but then add password(?))

**Should be fixed in some way on the client too (maybe just ask if the server is updated and notify about the vulnerability)**

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

### PR DESCRIPTION
**Pull request by 3arthqu4ke**

### CODE REVIEW

**Comment by 3arthqu4ke** [comment]
Fixes #136

**Comment by 3arthqu4ke** [comment]
Ok, wtf

**Comment by cattyngmd** [comment]
🔥

**Comment by cattyngmd** [comment]
codacy moment

**Comment by 3arthqu4ke** [comment]
WHAT

**Comment by 3arthqu4ke** [comment]
Yeah, this gets merged now, idc

**Pull request merged**
