### PR TITLE
V.1.8.6

### PR DESCRIPTION
**Pull request by 3arthqu4ke**

### CODE REVIEW

**Review by hiyama283 — APPROVED** [review]
ok refactor and additional Functions

**Comment by mdo992** [comment]
should i PR here or the main branch?

**Review by Zane2b2t — APPROVED** [review]

**Review by GentlemanMC — APPROVED** [review]
halal/10

**Review by cmetanamaker — COMMENTED** [review]
blyat delete this pls(my review)

**Comment by KaliCyanide** [comment]
based

**Review by cmetanamaker — COMMENTED** [review]
good

**Review by GRIFFiin — APPROVED** [review]

**Review by shxrkyylol — APPROVED** [review]
I APPROVE. GOOD CHANGES.

**Comment by shasdfasdqw** [comment]
and no update for 1 month

**Comment by GRIFFiin** [comment]
> and no update for 1 month

sad

**Review by ElBe-Plaq — APPROVED** [review]

**Pull request merged**
