### PR TITLE
Very Important PR

### PR DESCRIPTION
**Pull request by cattyngmd**

### CODE REVIEW

**Comment by 3arthqu4ke** [comment]
Can you try fix codacy pls :) :) :) :) ? Two spaces after each bullet/(1., 2. 3. etc.) point instead of one? (https://app.codacy.com/gh/3arthqu4ke/3arthh4ck/pullRequest?prid=10035609)

**Review by 3arthqu4ke — APPROVED** [review]

**Comment by cattyngmd** [comment]
> Can you try fix codacy pls :) :) :) :) ? Two spaces after each bullet/(1., 2. 3. etc.) point instead of one? (https://app.codacy.com/gh/3arthqu4ke/3arthh4ck/pullRequest?prid=10035609)

yeah

**Comment by cattyngmd** [comment]
hm

**Comment by 3arthqu4ke** [comment]
Screenshot 2022-08-24 002319
+2 -9 sounds good to me, will merge tomorrow. Fixing the lines 10 and 11 would be the icing on da cake.

**Comment by cattyngmd** [comment]
yeah

**Comment by cattyngmd** [comment]
okay so 2 digit bullets need 1 space and 1 digit bullets need 2. cool

**Comment by 3arthqu4ke** [comment]
wtf

**Comment by 3arthqu4ke** [comment]
ah kinda makes sense

I guess it changes too once you go to 3 digits

**Comment by 3arthqu4ke** [comment]
Thanks a lot! 🔥

**Comment by cattyngmd** [comment]
np

**Comment by cattyngmd** [comment]
> ah kinda makes sense
> 
> I guess it changes too once you go to 3 digits

i dont think that ppl need to go over 2 digits lol

**Pull request merged**
