### PR TITLE
README Changes

### PR DESCRIPTION
**Pull request by browsky300**
General cleanup and some extra information.

### CODE REVIEW

**Comment by Zane2b2t** [comment]
cat gif

**Comment by mdo992** [comment]
bro edited the readme to prob get added as a contributor and linked to his repo thats not even public

**Comment by Zane2b2t** [comment]
> 

Thats CRAZY broo

**Comment by mdo992** [comment]
> Thats CRAZY broo

ok bro

**Comment by browsky300** [comment]
> bro edited the readme to prob get added as a contributor and linked to his repo thats not even public

i couldnt care less if my name is on a minecraft client repo. I just redid some stuff bc it was kinda bothering me

**Pull request closed without merging**
