### PR TITLE
Phobos Main Menu Plugin

### PR DESCRIPTION
**Pull request by mdo992**
A port of the old phobos main menu with the earthhack button added.

Let me know if you need any more changes.

### CODE REVIEW

**Comment by mdo992** [comment]
Partially closes #175.

**Review by 3arthqu4ke — APPROVED** [review]
LGTM!

**Comment by 3arthqu4ke** [comment]
Maybe you wanna add yourself to the authors in the mcmod.info on the main branch? If you commit to the plugins branch you dont show up in the contributors and I cant credit you as a contributor in the next release.

**Comment by mdo992** [comment]
i'm good ty, most of the menu code is yours either way

**Pull request merged**
