### PR TITLE
[1.8.3] Surround - Movement - Y

### PR DESCRIPTION
**Pull request by 3arthqu4ke**

### CODE REVIEW

**Comment by Zane2b2t** [comment]
what does this do

**Comment by master7720** [comment]
"                " will disable itself.\n-Y if you move along the Y-Axis this " +
                "module will disable itself.\n-Limit If you move" +"

**Comment by Zane2b2t** [comment]
> " " will disable itself.\n-Y if you move along the Y-Axis this " + "module will disable itself.\n-Limit If you move" +"

Isn't that already a thing

**Comment by 3arthqu4ke** [comment]
Only for all axes, this will only turn the module off when you jump out. Will add a YPlus mode in a second.

**Pull request merged**
